### PR TITLE
Implement Design system on frontend

### PR DESCRIPTION
**Pull request by vertism**
## Description
Replace old gems with design system gems and govuk-frontend package.
Updates CSS and views to use design system components.

### CODE REVIEW

**Comment by lucas-shaw** [comment]
I had an error when trying to update ffi

```
An error occurred while installing ffi (1.15.5), and Bundler cannot continue.

In Gemfile:
  sass-rails was resolved to 6.0.0, which depends on
    sassc-rails was resolved to 2.1.2, which depends on
      sassc was resolved to 2.4.0, which depends on
        ffi
```

Updating ffi to 1.17.0 worked for me

**Comment by lucas-shaw** [comment]
I received an error message in the browser which was resolved running yarn in the terminal.

```
saasc::syntaxerror file to import not found or unreadable govuk-frontend/dist/govuk/all 
line 1:1 of app/assets/stylesheets/application.css.scss
```

**Comment by vertism** [comment]
> I received an error message in the browser which was resolved running `yarn` in the terminal.
> 
> ```
> saasc::syntaxerror file to import not found or unreadable govuk-frontend/dist/govuk/all 
> line 1:1 of app/assets/stylesheets/application.css.scss
> ```

Ah yes, I got that too. I will update the README.

**Review by lucas-shaw — COMMENTED** [review]
LGTM

**Pull request merged**
